spring:
  profiles:
    active: local
  mvc:
    locale: ko_KR
  messages:
    basename: classpath:/messages/message
    encoding: UTF-8
config:
  restTemplate:
    timeout: 5000
    maxConnTotal: 100
    maxConnPerRoute: 50
---
spring:
  profiles: local
server:
  port: 8001
---
spring:
  profiles: dev
server:
  port: 8001
